import Head from 'next/head'
import { motion } from 'framer-motion'
import Navbar from '../Navbar'
import Footer from '../Footer'

const variants = {
  hidden: { opacity: 0, x: 0, y: 50 },
  enter: { opacity: 1, x: 0, y: 0 },
  exit: { opacity: 0, x: 0, y: -100 },
}

const Layout = ({ title = 'Brolly', children, mainStyle }) => {
  return (
    <div className="">
      <Navbar />
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main
        variants={variants}
        initial="hidden"
        animate="enter"
        exit="exit"
        transition={{ ease: 'easeOut', duration: 1, type: 'linear' }}
        className={mainStyle}
      >
        {children}
      </motion.main>
      <Footer />
    </div>
  )
}

export default Layout
