import Head from 'next/head'
import Navbar from '../Navbar'
import Footer from '../Footer'

const Layout = ({ title = 'Brolly', children }) => {
  return (
    <div className="">
      <Navbar />
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>{children}</main>
      <Footer />
    </div>
  )
}

export default Layout
